### ISSUE TITLE
Column order of existing table not respected in columnar insert

### ISSUE THREAD

**Issue by jp-harvey** [omnisci/pymapd#100]
Tables can be created in OmniSci with the columns in a user specified order. However when a Pandas dataframe is created it automatically orders the columns alphabetically, with uppercase letters first. PyMapD does no check for this so as a result the columns can be ordered incorrectly on insert and either the wrong data is inserted into the column or an error is returned.

**Comment by jp-harvey** [comment]
Submitted https://github.com/omnisci/pymapd/pull/101

**Comment by jp-harvey** [comment]
Sample code, this produces the error:

```
mapd.ttypes.TMapDException: TMapDException(error_msg='load_table_binary_columnar: Input exception thrown: TException - service has thrown: TMapDException(error_msg=load_table_binary_columnar: Inconsistent number of rows in request,  expecting 1 row, column 3 has 0 rows). Issue at column : 4. Import aborted')
```

```
import pymapd
import pandas as pd

mapduser = 'mapd'
mapdpass = 'HyperInteractive'
mapdhost = 'localhost'
mapdport = 9090
mapdprotocol = 'http'
mapddbname = 'mapd'

mapdcon = pymapd.connect(user=mapduser, password=mapdpass, host=mapdhost, dbname=mapddbname, port=mapdport, protocol=mapdprotocol)
tbl = mapdcon.get_tables()

mapdtable = 'colordertest'

if mapdtable in tbl:
    print('Dropping table {0}'.format(mapdtable))
    c = mapdcon.cursor()
    c.execute('DROP TABLE {0};'.format(mapdtable))

createtablesql = 'CREATE TABLE colordertest ('
createtablesql += '    Id TEXT ENCODING NONE'
createtablesql += ',   AColumn TEXT ENCODING NONE'
createtablesql += ',   AnotherColumn BOOLEAN'
createtablesql += ',   ColumnFubar INT'
createtablesql += ');'

data = [
    {
        'Id': 'ID1',
        'AColumn': 'AColumn1',
        'AnotherColumn': 'AnotherColumn1',
        'ColumnFubar': 1,
    }
]

df = pd.DataFrame(data)

tbl = mapdcon.get_tables()
if mapdtable not in tbl:
    c = mapdcon.cursor()
    c.execute(createtablesql)

mapdcon.load_table(mapdtable,df,preserve_index=False)
```

**Comment by jp-harvey** [comment]
It is indeed a Pandas issue, I'm changing it so I don't have to write the same logic every time in my scripts :-)

**Comment by randyzwitch** [comment]
The more I think about this issue, the more I question whether this is something we want to do. Ultimately, the question is "what do we assume about inserting data into an already existing table?"

The solution in #101 assumes that key names from a Dict are the column names in the dataframe AND the column names of the table. However, isn't insert into OmniSci a positional operation? Meaning, it doesn't matter what the column names are for the pandas dataframe when a table exists, it just matters their position in a dataframe, which then gets pushed through the Thrift interface.

If so, ordering a pandas dataframe by the columns of an existing table doesn't necessarily work if the column names of the dataframe aren't the same as the OmniSci table. Especially given the case that in SQL, capitalization doesn't matter and in pandas it does, as well as pandas having a different set of reserved keywords than OmniSci does. So the solution here feels like special-casing a specific use case/bug in pandas, rather than a flaw in the pymapd implementation.

My recommendation here would not be to change the code, but recognize that the solution from the python side is either to use an OrderedDict, or have a debug mode of some kind to indicate that the column names don't match between the dataframe and the existing OmniSci table.

**Comment by jp-harvey** [comment]
I think that's a valid point. By no means is this a "flaw" in PyMapD, however many of our tools could have their usability improved greatly. It should probably be an option rather than automatic given the feedback above. I know myself I've burnt a lot of hours debugging code because there are either no errors or the errors are too obscure to immediately understand what is going on in much of our software. This is not a complaint but simply something to improve on.

**Comment by jp-harvey** [comment]
Closed by https://github.com/omnisci/pymapd/pull/129
