### ISSUE TITLE
Make pandas and pyarrow dependencies

### ISSUE THREAD

**Issue by randyzwitch** [omnisci/pymapd#119]
As part of cleaning up the codebase, it feels like we should just make pandas and pyarrow installed, rather than check within several methods to see if they are installed. We're already requiring NumPy, which is a heavy dependency; anyone with NumPy installed AND using a database shouldn't have an issue with pandas also being installed. 

The upside of this would be to remove a bunch of boilerplate testing for packages being installed.

Edit: And make NumPy >= 1.14 (NumPy is already a dependency)

**Comment by jp-harvey** [comment]
@randyzwitch something to think about here would be that by PyMapD automatically uses Arrow if it's installed, and it does not always work in cases where Pandas does so it would be a breaking change in some cases where Arrow was not already installed and the user was not specifically loading via Pandas.

That said I think at some point we should make it a requirement anyway since that seems to be the direction we're heading, and changing the auto load selection behavior which is a breaking change too so we should probably bite the bullet and make a breaking change now while the user base is still small.

**Comment by randyzwitch** [comment]
Good point, I was only thinking about download, where you already opt-in by choosing the `select_ipc` method; wasn't thinking about the magic `load_table` method :(

**Comment by randyzwitch** [comment]
Fixed by #120
