### ISSUE TITLE
Cleanup in support of default port changes

### ISSUE THREAD

**Issue by mflaxman10** [omnisci/pymapd#163]
There are at least 9 instances where port 9091 is hardcoded.

Since now Python 3, I'd propose all of these should be set to an enum scheme matching the config file.  Something like:

from enum import Enum
class OmniSciPort(Enum):
        DB= 6274
        WEB = 6273
        CALCITE = 6279

then in use:
OmniSciPort.DB
etc.

**Comment by randyzwitch** [comment]
I'm not sure I follow...you can set the port when you call `pymapd.connect()` which should allow you to switch to whatever you need for a given server.

We can change the default port in the package when OmniSci 4.5 comes out for convenience, but it doesn't feel like that needs an Enum scheme, because ultimately any of the ports can be changed by during install.
