### ISSUE TITLE
Current 0.4.0 release downgraded to 0.3.1 when pygdf installed

### ISSUE THREAD

**Issue by randyzwitch** [omnisci/pymapd#86]
If you install pymapd first through conda, then install pygdf with `conda install -c numba -c conda-forge -c gpuopenanalytics/label/dev -c defaults pygdf=0.1.0a3`, it will downgrade pymapd to 0.3.1

**Comment by andrewseidl** [comment]
This is probably due to older versions of pymapd not having a version specifier for pygdf, so they would accept any (potentially incompatible) version.

I'm about to push Arrow 0.10.0 to mapd-core and will push a dev core build to Docker Hub, which in turn will let us upgrade pymapd to pyarrow 0.10.0 and pygdf 0.1.0a3.

**Comment by randyzwitch** [comment]
This is fixed with pymapd 0.5.0
